### ISSUE TITLE
update to latest version of requests 

### ISSUE THREAD

**Issue by chelm** [TDG-Platform/gbdx-auth#15]
Say @saintsjd can we update or unpin the requests version used here? I have the latest installed locally but gbdxtools complains on its install about conflicts with this version in gbdx-auth: 

`error: requests 2.14.2 is installed but requests[security]==2.13.0 is required by set(['gbdx-auth'])`

**Comment by saintsjd** [comment]
I believe we can. We need to manually test though because there are no tests in gbdx auth repo. i can test for you later today and let you know.

**Comment by nricklin** [comment]
unpinned.
