### ISSUE TITLE
Edge case: Does it handle a revoked refresh_token?

### ISSUE THREAD

**Issue by colllin** [TDG-Platform/gbdx-auth#7]
Moved here from https://github.com/DigitalGlobe/gbdxtools/issues/59

> If a user's refresh_token is revoked/invalidated, does gbdxtools ask them to login again to obtain a new one? I can help you debug this if you need to. There's an API for revoking a refresh_token.

**Comment by youngpm** [comment]
Its not clear to me we want to actually retry in this case.  Currently, an exception will be raised in this situation and the user would need to go manually clear out the token from their config. 

Maybe we just want to clear the token stashed in the configuration?  When the user retried, they'd get a fresh one automatically...
